GET http://localhost/api/ingredients
Authorization: 0e16ccedb367764507ed40fdbe44280d6b961d8e
Content-Type: application/json

{
    "text": "test com text",
}

###
POST http://localhost/api/users/
Content-Type: application/json

{
"username": "admin3",
"password": "cjabz2007",
"email": "email1@email1.com",
"first_name": "Name",
"last_name": "Surname"
}

###
POST http://localhost/api/auth/token/login
Content-Type: application/json

{
    "email": "email1@email1.com",
    "password": "cjabz2007"
}

###
POST http://localhost/api/tags/
Content-Type: application/json

{
    "name": "asdasd",
    "color": "#222222",
    "slug": "asdasd"
}

###
GET http://localhost/api/users/
Authorization: Token 841bc3401f565ec57832441b64d7de3c3787c92d

###
GET http://localhost/api/recipes/