GET http://127.0.0.1:8000/api/ingredients
Authorization: 0e16ccedb367764507ed40fdbe44280d6b961d8e
Content-Type: application/json

{
    "text": "test com text",
}

###
POST http://127.0.0.1:8000/api/users/
Content-Type: application/json

{
"username": "aasd",
"password": "cjabz2007",
"email": "first@user.com",
"first_name": "Name",
"last_name": "Surname"
}

###
GET http://localhost/api/users/
#Authorization: Token ad1605a6182d432adb1ce07b63d11baad4cdc46b

###
GET http://127.0.0.1:8000/api/users/1/subscribe/
Authorization: Token 6ac53f2fcbe2bd720880cb636bc238b8176fcd54

###
POST http://127.0.0.1:8000/api/auth/token/login
Content-Type: application/json

{
    "email": "first@user.com",
    "password": "cjabz2007"
}

###
POST http://127.0.0.1:8000/api/tags/
Authorization: Token 64a773aacb1fda4bf4529173be9cb6ca89bc4b15
Content-Type: application/json

{
    "name": "green",
    "color": "#2ef542",
    "slug": "green"
}

###
GET http://127.0.0.1:8000/api/recipes/
Authorization: Token 6ac53f2fcbe2bd720880cb636bc238b8176fcd54

###
POST http://127.0.0.1:8000/api/recipes/1/shopping_cart/
Authorization: Token 6ac53f2fcbe2bd720880cb636bc238b8176fcd54

###
GET http://127.0.0.1:8000/api/recipes/download_shopping_cart/
Authorization: Token 6ac53f2fcbe2bd720880cb636bc238b8176fcd54

###
POST http://127.0.0.1:8000/api/recipes/1/favorite/
Authorization: Token 6ac53f2fcbe2bd720880cb636bc238b8176fcd54

###
POST http://127.0.0.1:8000/api/recipes/
Authorization: Token 6ac53f2fcbe2bd720880cb636bc238b8176fcd54
Content-Type: application/json

{
    "name": "5",
    "tags": [1],
    "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
    "text": "text#2",
    "ingredients": [
        {
        "id": 1123,
        "amount": 20
        },
        {"id": 1111,
         "amount": 1
         }
        ],
    "cooking_time": 100
        }

###
PATCH http://127.0.0.1:8000/api/recipes/11/
Content-Type: application/json

{
    "name": "edited recipe#2",
    "tags": [2],
    "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
    "text": "edited text#2",
    "ingredients": [
        {
        "id": 1123,
        "amount": 20
        },
        {"id": 1110,
         "amount": 10
         }
        ],
    "cooking_time": 100
        }

###
GET  http://localhost/admin