GET http://127.0.0.1:8000/api/ingredients
Authorization: 0e16ccedb367764507ed40fdbe44280d6b961d8e
Content-Type: application/json

{
    "text": "test com text",
}

###
POST http://127.0.0.1:8000/api/users/
Content-Type: application/json

{
"username": "admin",
"password": "cjabz2007",
"email": "asd@asd.com",
"first_name": "Name",
"last_name": "Surname"
}

###
GET http://127.0.0.1:8000/api/users/me
Authorization: Token e9bd23e45d15a293b9f278cf5c9de90f737fe4b4

###
POST http://localhost/api/users/1/subscribe/
Authorization: Token ad1605a6182d432adb1ce07b63d11baad4cdc46b

###
POST http://127.0.0.1:8000/api/auth/token/login
Content-Type: application/json

{
    "email": "asd@asd.com",
    "password": "cjabz2007"
}

###
GET http://localhost/api/tags/
Content-Type: application/json

{
    "name": "green",
    "color": "#2ef542",
    "slug": "green"
}

###
GET http://127.0.0.1:8000/api/recipes?is_favorited=1
Authorization: Token e9bd23e45d15a293b9f278cf5c9de90f737fe4b4

###
POST http://127.0.0.1:8000/api/recipes/1/favorite/
Authorization: Token e9bd23e45d15a293b9f278cf5c9de90f737fe4b4

###
POST http://127.0.0.1:8000/api/recipes/
Authorization: Token 386e8f35e3b74f3e7a1f3fc194e021601c0df8e8
Content-Type: application/json

{
    "name": "test pic",
    "tags": [1],
    "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
    "text": "text#2",
    "ingredients": [
        {
        "id": 1123,
        "amount": 20
        },
        {"id": 1111,
         "amount": 1
         }
        ],
    "cooking_time": 100
        }

###
PATCH http://127.0.0.1:8000/api/recipes/11/
Content-Type: application/json

{
    "name": "edited recipe#2",
    "tags": [2],
    "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
    "text": "edited text#2",
    "ingredients": [
        {
        "id": 1123,
        "amount": 20
        },
        {"id": 1110,
         "amount": 10
         }
        ],
    "cooking_time": 100
        }