# Generated by Django 2.2.19 on 2022-09-09 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220909_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagrecipe',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagrecipe', to='posts.Tags'),
        ),
    ]
