# Generated by Django 2.2.19 on 2022-09-09 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20220909_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='ingredients',
            field=models.ManyToManyField(related_name='ingredientrecipe', through='posts.RecipeIngredient', to='posts.Ingredients'),
        ),
    ]
